### ISSUE TITLE
add the title to the table of contents

### ISSUE THREAD

**Issue by balmas** [alpheios-project/grammar-bennett#1]
@abrasax would like us to add the title to the Table of Contents.

**Comment by balmas** [comment]
title should be there now.

**Comment by monzug** [comment]
I can see it. is it ok that back to index will point to Table of Contents and not to New Latin Grammar. I would say it's ok (user can always scroll up). @balmas, what do u think?
on mobile, back to index goes to top of the page so to the New Latin Grammar.

**Comment by balmas** [comment]
yes, I think so.  I will go ahead and move the anchor up though.

**Comment by monzug** [comment]
ok. I was ok with it.
